# Generated by Django 5.1.2 on 2024-10-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginusers',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
